/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectprueba;

import com.itextpdf.text.DocumentException;
import database.SeeClient;
import java.io.FileNotFoundException;
import java.io.FilePermission;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LFOM
 */
public class BusquedaClientes extends javax.swing.JFrame {
    
    //Object client to use for all methods
    SeeClient client = new SeeClient();
    
    /**
     * Creates new form BusquedaClientes
     */
    public BusquedaClientes() throws SQLException, ClassNotFoundException {
        initComponents();        
        //Work with database
        client.createNewDatabase(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        verClientes = new javax.swing.JButton();
        irAIngresarCliente = new javax.swing.JButton();
        imprimirClientes = new javax.swing.JButton();
        exitText = new javax.swing.JTextField();
        mainMenu = new javax.swing.JButton();
        enterClient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exitName = new javax.swing.JTextField();
        exitConcept = new javax.swing.JTextField();
        exitAddress = new javax.swing.JTextField();
        exitCuote = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        modifyData = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        deleteButtom = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        exitEmail = new javax.swing.JTextField();
        notifierButtom = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        verClientes.setText("Buscar");
        verClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verClientesActionPerformed(evt);
            }
        });

        irAIngresarCliente.setText("Nuevo cliente");
        irAIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irAIngresarClienteActionPerformed(evt);
            }
        });

        imprimirClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other/printer.png"))); // NOI18N
        imprimirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirClientesActionPerformed(evt);
            }
        });

        exitText.setBorder(null);

        mainMenu.setText("Menú principal");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        enterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterClientActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de cliente");

        jLabel2.setText("Nombre completo");

        jLabel3.setText("Dirección");

        jLabel6.setText("Cuota");

        modifyData.setText("modificar datos");
        modifyData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyDataActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other/clean.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Concepto");

        deleteButtom.setText("Borrar");
        deleteButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtomActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo electrónico");

        exitEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitEmailActionPerformed(evt);
            }
        });

        notifierButtom.setText("Enviar notificación");
        notifierButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifierButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imprimirClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(irAIngresarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterClient)
                        .addGap(18, 18, 18)
                        .addComponent(verClientes)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitText, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(exitCuote, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                            .addGap(77, 77, 77))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(exitName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(exitAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                                .addComponent(exitConcept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                                            .addGap(36, 36, 36)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(exitEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(modifyData)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(notifierButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verClientes))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(exitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(exitAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitConcept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(exitCuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyData)
                    .addComponent(deleteButtom)
                    .addComponent(notifierButtom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imprimirClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(irAIngresarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainMenu)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void verClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verClientesActionPerformed
        
        //To see client in interface        
        try {
            
            //This variable contains the number of rows obtains for the query
            String numeroClientes = client.numberOfRows("nombre", enterClient.getText());
            //Show in the text fields all the information if data exist
            if (numeroClientes.equals("0")){
                
                exitText.setText("No hay datos, introduzca el nombre correctamente");
            
            } else {           
                
                exitName.setText( client.wantClient("nombre", enterClient.getText()) );
                exitAddress.setText( client.wantClient("direccion", enterClient.getText()) );
                exitConcept.setText( client.wantClient("materia", enterClient.getText()) );
                exitCuote.setText( client.wantClient("cuota", enterClient.getText()) );
                exitEmail.setText(client.wantClient("email", enterClient.getText()) );
            } //End if else    
            
                        
        } catch (SQLException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        //End of try catch
         //End of try catch  
                       
    }//GEN-LAST:event_verClientesActionPerformed

    private void irAIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irAIngresarClienteActionPerformed
        //Send to Client class
        try {
            //Return to Client class
            Clientes clientes = new Clientes ();
            clientes.setVisible(true);
            dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_irAIngresarClienteActionPerformed

    private void imprimirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirClientesActionPerformed
        // TODO add your handling code here:        
        try {
            
                                   
            //Create a PDF with clients (SeeClient.java class)
            client.clientInPDF();
            exitText.setText("Se ha creado un pdf con la lista total de clientes (En la carpeta Documentos)");
            //file permission
            FilePermission permission = new FilePermission("C:/Users/"+System.getProperty("user.name")+"/Documents/clientes.pdf", "read");            
            //Open the PDF document from his path *user.name = name of the current user*            
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:/Users/"+System.getProperty("user.name")+"/Documents/clientes.pdf");
                        
        } catch (SQLException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
            exitText.setText("Error a la hora de crear un documento PDF");
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
            exitText.setText("ERROR no se pudo abrir el PDF");
        } // End try catch
    }//GEN-LAST:event_imprimirClientesActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        
        //Go to main menu
        MainMenu cambiarVista = null;
        try {
            cambiarVista = new MainMenu ();
        } catch (SQLException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        cambiarVista.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_mainMenuActionPerformed

    private void enterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterClientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Clean all the fields
        exitText.setText("");
        exitName.setText("");
        exitAddress.setText("");
        exitConcept.setText("");
        exitCuote.setText("");
        exitEmail.setText("");
        enterClient.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modifyDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyDataActionPerformed
        
        //Check if fields are empty
        if ( enterClient.getText().trim().isEmpty() || exitName.getText().trim().isEmpty() || exitAddress.getText().trim().isEmpty() || exitCuote.getText().trim().isEmpty() || exitConcept.getText().trim().isEmpty() ) {
            
            exitText.setText("No puede haber campos vacios para modificar cliente");
            
        } else {
            
            //update the client with other data
            try {
                client.updateClient( enterClient.getText(), exitName.getText(), exitAddress.getText(), exitConcept.getText(), exitCuote.getText() );
                exitText.setText("cliente actualizado con éxito");
            } catch (SQLException ex) {
                Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
                exitText.setText("ERROR al modificar datos, contacte con el administrador");
            } //end try catch
            
        } //end alese
        
    }//GEN-LAST:event_modifyDataActionPerformed

    private void deleteButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtomActionPerformed
        
        //Check if field are empty
        if (enterClient.getText().trim().isEmpty()) {
            
            exitText.setText("seleccione un cliente para borrar");
            
        } else {
            
            try {
                // TODO add your handling code here:
                client.deleteClient("clientes", enterClient.getText());
                exitText.setText(enterClient.getText()+" ha sido borrado con éxito");
            } catch (SQLException ex) {
                Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
                exitText.setText("ERROR No ha sido posible borrar el cliente");
            } //end of try catch
            
        } //End of if/else
        
    }//GEN-LAST:event_deleteButtomActionPerformed

    private void notifierButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifierButtomActionPerformed
        // TODO add your handling code here:
        
        //Check if field email and name are empty
        if (exitEmail.getText().trim().isEmpty() || enterClient.getText().trim().isEmpty() ) {
            
            exitText.setText("Debes buscar un cliente para mandar una notificación");
            
        } else {
            //Go to client notifier
            ClientNotifier clientNotifier = new ClientNotifier ();
            clientNotifier.setVisible(true);
            dispose();
            
        } //End if else
        
    }//GEN-LAST:event_notifierButtomActionPerformed

    private void exitEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new BusquedaClientes().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(BusquedaClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButtom;
    private javax.swing.JTextField enterClient;
    private javax.swing.JTextField exitAddress;
    private javax.swing.JTextField exitConcept;
    private javax.swing.JTextField exitCuote;
    public static javax.swing.JTextField exitEmail;
    private javax.swing.JTextField exitName;
    private javax.swing.JTextField exitText;
    private javax.swing.JButton imprimirClientes;
    private javax.swing.JButton irAIngresarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton mainMenu;
    private javax.swing.JButton modifyData;
    private javax.swing.JButton notifierButtom;
    private javax.swing.JButton verClientes;
    // End of variables declaration//GEN-END:variables
}
